branch-defaults:
  development:
    environment: Dev-env
environment-defaults:
  Dev-env:
    branch: null
    repository: null
global:
  application_name: Demo-Application
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.8.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: demo
  sc: git
  workspace_type: Application
